//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Visualization
{
    [Serializable]
    public class MeshFileMsg : Message
    {
        public const string k_RosMessageName = "visualization_msgs/MeshFile";
        public override string RosMessageName => k_RosMessageName;

        //  Used to send raw mesh files.
        //  The filename is used for both debug purposes and to provide a file extension
        //  for whatever parser is used.
        public string filename;
        //  This stores the raw text of the mesh file.
        public byte[] data;

        public MeshFileMsg()
        {
            this.filename = "";
            this.data = new byte[0];
        }

        public MeshFileMsg(string filename, byte[] data)
        {
            this.filename = filename;
            this.data = data;
        }

        public static MeshFileMsg Deserialize(MessageDeserializer deserializer) => new MeshFileMsg(deserializer);

        private MeshFileMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.filename);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filename);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "MeshFileMsg: " +
            "\nfilename: " + filename.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
