//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Visualization
{
    [Serializable]
    public class UVCoordinateMsg : Message
    {
        public const string k_RosMessageName = "visualization_msgs/UVCoordinate";
        public override string RosMessageName => k_RosMessageName;

        //  Location of the pixel as a ratio of the width of a 2D texture.
        //  Values should be in range: [0.0-1.0].
        public float u;
        public float v;

        public UVCoordinateMsg()
        {
            this.u = 0.0f;
            this.v = 0.0f;
        }

        public UVCoordinateMsg(float u, float v)
        {
            this.u = u;
            this.v = v;
        }

        public static UVCoordinateMsg Deserialize(MessageDeserializer deserializer) => new UVCoordinateMsg(deserializer);

        private UVCoordinateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.u);
            deserializer.Read(out this.v);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.u);
            serializer.Write(this.v);
        }

        public override string ToString()
        {
            return "UVCoordinateMsg: " +
            "\nu: " + u.ToString() +
            "\nv: " + v.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
